### ISSUE TITLE
ideas for varying additional model parameters and additional outcome measure

### ISSUE THREAD

**Issue by alyson-singleton** [eehh-stanford/MinMaj-Adaptation-Diffusion#4]
after rereading the draft, i had a few ideas of model parameters we could vary to add a dimension to the paper. i will be very interested to hear whether the rest of the team thinks including any of these is worth the trouble and/or which is the most motivated out of the field's current outstanding questions:

1. having unequal homophily values. as I currently understand it, in-group preferences are set globally (equal for all agents?). this often varies non-randomly in real life, with examples i've seen in the past having higher homophily values in the minority / marginalized group.
2. Is every agent given an opportunity to learn at each time point? would also guess this varies between majority/minority *and* where the adaptation originated (or is this sort of dynamic fully captured in the implementation of the fitness parameter?)
3. i have mentioned this before, but i think varying the total population size could also be extremely interesting. maybe the results are boring but maybe not. even if it is a very predictable result, could be good to say we tested it (and perhaps include supplementary figures?)

PS a final suggestion for an additional outcome measure (which totally might be beyond the scope of the paper): the *time* it takes to reach fixation--could build "epidemic (transmission?) curves" ?

**Comment by mt-digital** [comment]
Thanks, Aly! This is helpful on a number of levels. 

1. Yes, let's try to test asymmetric homophily values. This is something we'll be able to do in the stochastic agent-based and deterministic selective-mixing model (#1)

2. Currently we do assume that each agent learns at every iteration. We could modify this, but I suspect that this assumption better matches the deterministic selective-mixing model.

3. We do need sensitivity analyses for the number of agents, $N$. There could be interesting changes, and like you say it's important to see the differences whether or not it changes the outcome.

4. Regarding the measurement of time to fixation, I agree this could be interesting. In terms of evolution this could be interpreted as evolutionary drift. I think this could be theoretically important because it may take the population longer to find a solution for a given homophily setting, even if that setting leads to more sustainable outcomes.

**Comment by mt-digital** [comment]
There are three sets of to-dos I'll put here that need to be done to close this issue. Time to fixation should be done first since we want to track this variable for $N$ sensitivity analyses and asymmetric homophily.

### Time to fixation

- [x] add logic to find max iteration number in output data, add to joined `adata`-`mdata` `DataFrame`
- [x] plot mean of fixation times over independent variables, for now separate from Sustainability axes

### $N$ sensitivity

- [x] create slurm scripts to automate runs
- [x] develop plotting/display for them (maybe simple as posting in subfigures in SI)

### Asymmetric homophily

- [x] add `homophily_1` and `homophily_2` parameters to `experiment.jl` and `model.jl` code
- [x] add elements to `mdata` list to report $h_1$ and $h_2$ in output data
- [x] create bash and slurm scripts to run a range of $h_1$, $h_2$ 
- [x] heatmap to calculate sustainability (color axis) over $h_1$ and $h_2$ on x- and y-axes.

**Comment by mt-digital** [comment]
Here's a new checklist with the full range of sensitivity analyses we need. To do this we need bash/slurm scripts and to use job arrays, which involves partitioning outputs, to keep runs to ~1.5h per 100 trials. Thus with 10 jobs per array the whole 1000 trials will finish in ~1.5h for one start group condition ("minority", "majority", or "both"). Set $N=1000$, $m=0.05$, and $f(a) = 1.2$ unless otherwise specified.

- [x] $m$ sensitivity over $m=0.2,0.5$ 
- [x] $f(a)$ sensitivity over $f(a)=1.05,1.4,2.0$

We still need an analysis of time to fixation for each parameter setting, but since this is not central to the analysis I suspect it should go in the Supplement.

**Comment by mt-digital** [comment]
@alyson-singleton thanks again for raising this issue! Closing now that we did this analysis that's under review :)
